Added multitenancy for storage backend
snkeos/fhir-works-on-aws-persistence-ddb pull request #2
Opened 2021-08-04 09:14 UTC by MarioDegen

Description of changes:
Forward tenantId to the dynamodb table.
The table key is an composite key (resourceid + tenantId) if multitenancy is enabled, tenantid is also separately stored in a column.
Utility functions are implemented to create the composite key and to extract the resource id and tenant id again.
For ddb to elasticsearch the resource id and tenant id are stored separately. The tenant id is also configured as index.
Added tests
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-01 11:03 UTC, ilyash-b requested changes
* See comments
* Can (resource id + resource id) aspect be done more clear somehow?

2021-09-01 11:03 UTC, ilyash-b commented on src/objectStorageService/s3DataService.test.ts
> +async function runCreateV4Test(s3DataService: S3DataService, tenantId?: string) {
With and without tenantId tests are factored out - good!

2021-11-12 17:48 UTC, MarioDegen commented on src/dataServices/dynamoDbUtil.ts
> +            }
During transaction handling it is necessary that getMostRecentResources returns the resource including the tenantid, with can be controlled by the projection expression

2022-01-25 20:15 UTC, ilyash-b requested changes
The amount of changes is huge. I strongly recommend different tradeoff: a bit more magic, much less code.

* Change resource `id` from `string` (primitive type) to `String` object. This allows arbitrary fields on the instances.
* Transform `id` and `tenantId` to new (concatenated or whatever) `id` as soon as possible, this will make the change transparent to most of the code
* Pass tenant id and original `id` along with the new (concatenated) `id`
* The above will eliminate most of the occurrences of `tenantId` and the need to pass it
* The places that need the original id and tenant id (few, low level places in the code)
* There can be several places in the code where this will not go smooth, talk to me if needed

See the code below for more information:
```
// Allow .fhirWorksTenantId on the built-in String type
interface String {
    fhirWorksOriginalResourceId: string;
    fhirWorksTenantId?: string;
}

// demo function with "string" type parameter
function f(s:string) {
}

f('aaa'); // works ok, argument type matches parameter type "string"

// vscode did not show any warning about the code line below
// https://www.jetbrains.com/help/idea/disabling-and-enabling-inspections.html#suppress-inspections
// noinspection JSPrimitiveTypeWrapperUsage
const s = new String('aaa');

s.fhirWorksTenantId = 'blah'; // works because of the interface definition at the top of the file

// f(s); // tsc: error TS2345: Argument of type 'String' is not assignable to parameter of type 'string'

f(s as string); // type cast, also works

// Solution rough idea - start
class DynamoDbUtil {
    // should probably move, the method is more generic than DynamoDb
    static buildItemId(resourceId: string, tenantId?: string): string {
        // noinspection JSPrimitiveTypeWrapperUsage
        const ret = new String(resourceId + (tenantId || ''));
        ret.fhirWorksOriginalResourceId = resourceId;
        ret.fhirWorksTenantId = tenantId;
        return ret as string;
    }
}

const id = DynamoDbUtil.buildItemId('rrr', 'ttt');
console.log(JSON.stringify(id)); // correct, "rrrttt"
console.log(id.fhirWorksOriginalResourceId);
console.log(id.fhirWorksTenantId);

// Solution rough idea - end
```

2022-01-27 08:59 UTC, MarioDegen commented
Hi @ilyash-b this is approach makes more sense. Is there also typescript an option the override cast operators, like in c++? So that f(s); would also work. Thx a lot for that feedback!
Next week I try it out and start with snkeos/fhir-works-on-aws-interface.

2022-01-28 17:06 UTC, ilyash-b commented
> Is there also typescript an option the override cast operators, like in c++? So that f(s); would also work.

Not aware of such thing

2022-03-16 17:30 UTC, closed without merging